version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db01
    ports:
      - "5412:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: employee_backend00
    ports:
      - "3412:3412"
    env_file:
      - ./Backend/server.env
    depends_on:
      - postgres
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./Backend/public:/app/public

  frontend:
    build: ./Frontend
    container_name: employee_frontend00
    ports:
      - "8036:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html:ro

volumes:
  pgdata:

